name: "Checkmate – Uptime Monitor"
description: "Open-source uptime and infrastructure monitoring with a built-in MongoDB."
version: "1.0.1"
slug: "checkmate"
url: "https://github.com/DaHofa02/dahofa-ha-addons/tree/main/checkmate"

image: "ghcr.io/dahofa02/dahofa-ha-addons-checkmate-{arch}"

arch:
  - amd64
  - aarch64

startup: application
boot: auto

ports:
  52345/tcp: 52345
ports_description:
  52345/tcp: "Checkmate Web UI & API"

map:
  - type: share
    read_only: false

options:
  jwt_secret: "change_me_please"
  mongodb_port: 27017
  base_url: "http://localhost:52345"

schema:
  jwt_secret: str
  mongodb_port: int
  base_url: str

ingress: true
ingress_port: 52345
ingress_stream: true
panel_icon: "mdi:monitor-eye"
panel_title: "Checkmate"

tmpfs: true

changelog: "https://github.com/DaHofa02/dahofa-ha-addons/blob/main/checkmate/CHANGELOG.md"
